name: 'Run App'

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest  # Change to Windows runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.301'  # You can use .NET 5 or any version you need

      - name: Restore dependencies
        run: dotnet restore GithubActions.sln

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal
