name: 'Run App'

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest  # Use Windows runner for .NET Framework 4.8 compatibility

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.301'  # or the appropriate version

      - name: Restore dependencies
        run: dotnet restore GithubActions.sln

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal
